import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const firaCode = Fira_Code({
  variable: "--font-fira",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.variable} antialiased bg-black px-2`}
        cz-shortcut-listen="true"
      >
        <header className="w-full top-0 z-50 bg-black backdrop-blur px-2">
          <Navbar />
        </header>
        <main className="relative">{children}</main>
      </body>
    </html>
  );
}
